---
apiVersion: v1
kind: Pod
metadata:
  name: trail3
spec:
  containers:
    - name: mysql
      image: mysql:8.0-debian
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: admin123
        - name: MYSQL_DATABASE
          value: emp
        - name: MYSQL_USER
          value: nop
        - name: MYSQL_PASSWORD
          value: admin123