apiVersion: v1
kind: Pod
metadata:
  name: notoleration
  labels:
    name: notoleration
spec:
  containers:
  - name: notoleration
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
