apiVersion: v1
kind: Pod
metadata:
  name: bpod
  labels:
    name: bpod
spec:
  containers:
  - name: bpod
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
