---
apiVersion: v1
kind: Pod
metadata:
  name: init-demo
spec:
  containers:
    - name: httpd
      image: httpd
      ports:
        - containerPort: 80
  initContainers:
    - name: delay
      image: alpine
      command:
        - sleep
        - 15s
    - name: init-myservice
      image: busybox:1.28
      command: 
        - 'sh' 
        - '-c' 
        - "until nslookup nginx-svc.default.svc.cluster.local; do echo waiting for myservice; sleep 2; done"
