---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-cm
data:
  MYSQL_ROOT_PASSWORD: admin123
  MYSQL_DATABASE: mydb
  MYSQL_USER: myuser
  MYSQL_PASSWORD: mypassword
---
apiVersion: v1
kind: Pod
metadata:
  name: cm-pod
  labels:
    app: alpine-demo
spec:
  containers:
    - name: alpine
      image: alpine:latest
      command: ["sh", "-c", "echo 'Hello from Alpine Pod'; sleep 3600"]
      volumeMounts:
        - name: cm-vol
          mountPath: /cm-demo
  volumes:
    - name: cm-vol
      configMap:
        name: mysql-cm
