---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-svc
spec:
  type: {{ .Values.service.type }}
  ports: {{ .Values.service.ports  | toYaml  | nindent 4 }}
  selector: {{ .Values.labels | toYaml | nindent 4}}